org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

mod_id=temple
mod_name=SighsTemple
mod_license=All Rights Reserved
mod_version=1.0.0-SNAPSHOT
mod_group_id=cc.sighs.temple
mod_authors=
mod_description=A blank multi-loader Minecraft development template.

forge_minecraft_version=1.20.1
forge_version=47.3.0
forge_version_range=[47,)
forge_loader_version_range=[47,)

fabric_minecraft_version=1.20.1
fabric_loader_version=0.16.14

neoforge_121_minecraft_version=1.21.1
neoforge_121_version=21.1.234
neoforge_121_version_range=[21.1,)

neoforge_261_minecraft_version=26.1
neoforge_261_version=26.1.2
neoforge_261_version_range=[26.1,)

