pluginManagement {
    repositories {
        gradlePluginPortal()
        maven { url = 'https://maven.minecraftforge.net/' }
        mavenCentral()
    }
}

rootProject.name = 'SighsTemple-forge-1.20.1'
includeBuild('../../common')

include 'common'
project(':common').projectDir = file('../../common')

